package e

const (
	SUCCESS        = 200
	ERROR          = 500
	INVALID_PARAMS = 400
)

const (
	ERROR_EXIST_TAG = 10001 + iota
	ERROR_NOT_EXIST_TAG
	ERROR_NOT_EXIST_ARTICLE
)

const (
	ERROR_AUTH_CHECK_TOKEN_FAIL = 20001 + iota
	ERROR_AUTH_CHECK_TOKEN_TIMEOUT
	ERROR_AUTH_TOKEN
	ERROR_AUTH
)

const (
	ERROR_UPLOAD_SAVE_IMAGE_FAIL = 30001 + iota
	ERROR_UPLOAD_CHECK_IMAGE_FAIL
	ERROR_UPLOAD_CHECK_IMAGE_FORMAT
)
